# (nombre, español, inglés) — textos tomados de apps/web/src/i18n.ts salvo los marcados «nativo».
S = [
# Splash (SPEC-v2 §4)
("splash_line1","Conecta humanos, empresas y bots","Connects humans, companies & bots"),
("splash_line2","Cada empresa. Cada canal.","Every company. Every channel."),
("splash_line3","Un solo hilo.","One thread."),
("splash_a11y","TieComs. Toca para continuar.","TieComs. Tap to continue."),
# Navegación
("nav_home","Inicio","Home"),
("nav_issues","Asuntos","Issues"),
("nav_agenda","Agenda","Agenda"),
("nav_settings","Ajustes","Settings"),
("nav_trazo","Trazo","Trace"),
("nav_whatsapp","WhatsApp","WhatsApp"),
# Auth
("auth_or_email","o con tu correo","or with your email"),
("auth_sso_needs_company","Escribe el nombre de tu empresa antes de continuar.","Type your company name before continuing."),
("auth_back_to_login","Volver a entrar","Back to sign in"),
("err_domain_claimed","Tu empresa ya está en TieComs. Pide a su administrador que te invite.","Your company is already on TieComs. Ask its administrator to invite you."),
("err_sso_state","No pudimos confirmar el inicio de sesión en este navegador. Inténtalo de nuevo.","We could not confirm the sign-in in this browser. Please try again."),
("err_sso_cancelled","Cancelaste el inicio de sesión.","You cancelled the sign-in."),
("err_sso_failed","No pudimos completar el inicio de sesión.","We could not complete the sign-in."),
("err_sso_unavailable","Este inicio de sesión aún no está disponible.","This sign-in is not available yet."),
("err_sso_personal_account","Usa tu cuenta de Microsoft de trabajo; las cuentas personales no están habilitadas.","Use your work Microsoft account; personal accounts are not enabled."),
("err_sso_email_unverified","Tu proveedor no ha verificado este correo. Entra con tu correo y contraseña.","Your provider has not verified this email. Sign in with your email and password."),
("err_account_disabled","Esta cuenta está desactivada.","This account is disabled."),
# Menús
("menu_reply","Responder","Reply"),
("menu_copy_text","Copiar texto","Copy text"),
("menu_copy_link","Copiar enlace","Copy link"),
("menu_pin","Fijar mensaje","Pin message"),
("menu_unpin","Quitar de fijados","Unpin"),
("menu_remind","Recordarme","Remind me"),
("menu_mark_unread","Marcar como no leído desde aquí","Mark unread from here"),
("menu_derive","Derivar a otra conversación","Branch into a new conversation"),
("menu_issue","Abrir asunto","Open issue"),
("menu_meeting","Agendar reunión","Schedule a meeting"),
("menu_forward","Reenviar","Forward"),
("menu_edit","Editar","Edit"),
("menu_delete","Eliminar mensaje","Delete message"),
("menu_delete_confirm","¿Eliminar este mensaje? Se verá como «Mensaje eliminado».","Delete this message? It will show as “Message deleted”."),
("menu_open","Abrir","Open"),
("menu_pin_top","Fijar arriba","Pin to top"),
("menu_unpin_top","Desfijar","Unpin"),
("menu_mark_read","Marcar como leído","Mark as read"),
("menu_mark_unread_conv","Marcar como no leído","Mark as unread"),
("menu_mute","Silenciar","Mute"),
("menu_unmute","Reactivar notificaciones","Unmute"),
("menu_leave","Salir del grupo","Leave group"),
("menu_more","Más opciones","More options"),
("chat_leave_confirm","¿Salir de este grupo?","Leave this group?"),
("when_20m","En 20 minutos","In 20 minutes"),
("when_1h","En 1 hora","In 1 hour"),
("when_3h","En 3 horas","In 3 hours"),
("when_tomorrow","Mañana a las 9:00","Tomorrow at 9:00"),
("when_monday","El lunes a las 9:00","Monday at 9:00"),
("when_custom","Elegir fecha y hora…","Pick date and time…"),
("mute_1h","Por 1 hora","For 1 hour"),
("mute_8h","Por 8 horas","For 8 hours"),
("mute_week","Por 1 semana","For 1 week"),
("mute_forever","Hasta que lo reactive","Until I turn it back on"),
("fwd_tiecoms","A otra conversación de TieComs…","To another TieComs conversation…"),
("fwd_whatsapp","Por WhatsApp","Via WhatsApp"),
("fwd_slack","Copiar para Slack","Copy for Slack"),
("fwd_email","Por correo","Via email"),
("fwd_teams","Copiar para Teams","Copy for Teams"),
("toast_copied","Copiado","Copied"),
("toast_link_copied","Enlace copiado · solo abre para quien tiene acceso","Link copied · only opens for people with access"),
("toast_slack_copied","Copiado con formato de Slack · pégalo en el canal","Copied with Slack formatting · paste it in the channel"),
("toast_teams_copied","Copiado · pégalo en Teams","Copied · paste it in Teams"),
("toast_reminder_set","Te lo recuerdo %1$s","I will remind you %1$s"),
("toast_pinned","Fijado","Pinned"),
("toast_unpinned","Quitado de fijados","Unpinned"),
("toast_muted","Silenciado","Muted"),
("toast_unmuted","Notificaciones reactivadas","Notifications back on"),
("toast_marked_unread","Marcado como no leído","Marked as unread"),
("toast_sent","Enviado","Sent"),
# Respuesta, edición, fijados
("reply_to","Respondiendo a %1$s","Replying to %1$s"),
("reply_cancel","Cancelar respuesta","Cancel reply"),
("reply_quote_missing","Respuesta a un mensaje anterior","Reply to an earlier message"),
("msg_edited","(editado)","(edited)"),
("edit_title","Editar mensaje","Edit message"),
("edit_save","Guardar","Save"),
("pins_title","Fijados","Pinned"),
("pins_empty","No hay mensajes fijados.","No pinned messages."),
("pins_count","%1$d fijados","%1$d pinned"),
("side_pinned","Fijados","Pinned"),
("side_muted","Silenciado","Muted"),
# Reenvíos e importar
("fwd_title","Reenviar a TieComs","Forward to TieComs"),
("fwd_search","Buscar conversación","Search conversation"),
("fwd_comment","Agregar un comentario (opcional)","Add a comment (optional)"),
("fwd_send","Reenviar","Forward"),
("fwd_from","Reenviado desde %1$s","Forwarded from %1$s"),
("fwd_from_by","Reenviado desde %1$s · %2$s","Forwarded from %1$s · %2$s"),
("fwd_from_conv","Reenviado desde «%1$s»","Forwarded from “%1$s”"),
("src_whatsapp","WhatsApp","WhatsApp"),
("src_slack","Slack","Slack"),
("src_email","correo","email"),
("src_teams","Teams","Teams"),
("src_tiecoms","TieComs","TieComs"),
("src_other","otra app","another app"),
("imp_action","Traer desde WhatsApp, Slack o correo","Bring from WhatsApp, Slack or email"),
("imp_title","Traer a TieComs","Bring to TieComs"),
("imp_body","Pega lo que copiaste de WhatsApp, Slack, un correo u otra app. Queda marcado con su origen y su autor original.","Paste what you copied from WhatsApp, Slack, an email or another app. It is marked with its origin and original author."),
("imp_source","Desde","From"),
("imp_paste","Pega aquí el mensaje, el hilo o el correo","Paste the message, thread or email here"),
("imp_author","Autor original (opcional)","Original author (optional)"),
("imp_detected","Detecté %1$d mensajes de WhatsApp","I detected %1$d WhatsApp messages"),
("imp_as_many","Traerlos como %1$d mensajes separados","Bring them as %1$d separate messages"),
("imp_as_one","Traerlo como un solo mensaje","Bring it as a single message"),
("imp_send","Traer","Bring"),
("imp_subject","Asunto: %1$s","Subject: %1$s"),
("share_title","Compartir en TieComs","Share to TieComs"),
("share_body","Elige dónde publicar lo que compartiste.","Choose where to post what you shared."),
("share_empty","No llegó texto para compartir.","No text arrived to share."),
# Recordatorios
("rem_title","Recordatorios","Reminders"),
("rem_due","Ahora","Now"),
("rem_upcoming","Próximos","Upcoming"),
("rem_empty","Sin recordatorios pendientes.","No pending reminders."),
("rem_done","Hecho","Done"),
("rem_snooze","Posponer 1 h","Snooze 1 h"),
("rem_custom","Recordarme","Remind me"),
("rem_when","Cuándo","When"),
("rem_note","Nota (opcional)","Note (optional)"),
("rem_save","Guardar recordatorio","Save reminder"),
("rem_about","Sobre «%1$s»","About “%1$s”"),
("rem_alert","Recordatorio","Reminder"),
("rem_date","Fecha","Date"),
("rem_time","Hora","Time"),
# Asuntos
("issue_new","＋ Asunto","＋ Issue"),
("issue_new_title","Nuevo asunto","New issue"),
("issue_from_message","＋ Abrir asunto","＋ Open issue"),
("issue_title","Qué hay que resolver","What needs to be solved"),
("issue_owner","Responsable","Owner"),
("issue_due","Fecha límite","Due date"),
("issue_no_due","Sin fecha","No date"),
("issue_create","Abrir asunto","Open issue"),
("issue_status","Estado","Status"),
("issue_st_open","Abierto","Open"),
("issue_st_in_progress","En curso","In progress"),
("issue_st_waiting","Esperando","Waiting"),
("issue_st_done","Resuelto","Done"),
("issue_st_cancelled","Descartado","Dropped"),
("issue_waiting_on","Esperando a","Waiting on"),
("issue_waiting_on_ph","Elige una empresa","Pick a company"),
("issue_here","Asuntos aquí","Issues here"),
("issue_origin","Ver mensaje de origen","See original message"),
("issue_origin_out","El mensaje de origen quedó fuera de tu historial","The original message is outside your history"),
("issue_requested_by","Lo pidió %1$s","Requested by %1$s"),
("issue_manual","Creado a mano","Created manually"),
("issue_stalled","Detenido hace %1$d días","Stalled for %1$d days"),
("issue_stalled_one","Detenido hace 1 día","Stalled for 1 day"),
("issue_overdue","Vencido","Overdue"),
("issue_today","Vence hoy","Due today"),
("issue_comment","Comentar","Comment"),
("issue_comment_ph","Escribe un avance o una pregunta…","Write an update or a question…"),
("issue_history","Historial","History"),
("issue_no_issues","No hay asuntos abiertos aquí.","No open issues here."),
("issue_mine","Míos","Mine"),
("issue_all_open","Abiertos","Open"),
("issue_closed","Cerrados","Closed"),
("issue_page_sub","Lo que quedó pendiente en tus conversaciones, con responsable y fecha. Cada asunto guarda el mensaje donde nació y solo lo ve quien puede leer esa conversación.","What was left pending in your conversations, with an owner and a date. Every issue keeps the message it came from, and only people who can read that conversation see it."),
("issue_empty","No hay asuntos con este filtro.","No issues match this filter."),
("issue_in","en %1$s","in %1$s"),
("issue_ev_created","abrió el asunto","opened the issue"),
("issue_ev_status","cambió el estado a %1$s","changed the status to %1$s"),
("issue_ev_owner","cambió el responsable","changed the owner"),
("issue_ev_due","cambió la fecha a %1$s","changed the date to %1$s"),
("issue_ev_title","renombró el asunto","renamed the issue"),
("issue_ev_waiting","marcó que se espera a otra empresa","marked it as waiting on another company"),
("issue_bottleneck","Posible cuello de botella","Possible bottleneck"),
("common_none","Nadie","Nobody"),
("common_save","Guardar","Save"),
("common_guest","Tercero invitado","Guest"),
("common_participant","Participante","Participant"),
("common_direct_message","Mensaje directo","Direct message"),
("kind_direct","Directo","Direct"),
# Derivar / linaje / trazo
("derive_action","⑂ Derivar","⑂ Branch"),
("derive_title","Derivar una conversación","Branch a conversation"),
("derive_body","Resuelve esta parte aparte, sin mover el hilo original. Cuando termines, devuelves el resultado aquí.","Solve this part separately without moving the original thread. When you are done, you return the result here."),
("derive_same","Grupo derivado · misma audiencia","Branched group · same audience"),
("derive_same_note","Sigue con las mismas personas y empresas de este grupo","Continues with the same people and companies as this group"),
("derive_internal","Diagnóstico interno · %1$s","Internal diagnosis · %1$s"),
("derive_internal_note","Solo tu empresa resuelve y devuelve la respuesta","Only your company works on it and returns the answer"),
("derive_directive","Decisión directiva","Leadership decision"),
("derive_directive_note","Quien lidera el espacio, tú y quien escribió el mensaje","The space leads, you and whoever wrote the message"),
("derive_name","Nombre","Name"),
("derive_reason","Por qué se deriva (opcional)","Why it is branched (optional)"),
("derive_create","Derivar","Branch"),
("derive_prefix_same","Derivada","Branch"),
("derive_prefix_internal","Diagnóstico","Diagnosis"),
("derive_prefix_directive","Decisión","Decision"),
("lin_label","Linaje","Lineage"),
("lin_from","Viene de «%1$s»","Comes from “%1$s”"),
("lin_from_hidden","Viene de una conversación fuera de tu alcance","Comes from a conversation outside your scope"),
("lin_kids","Derivó en","Branched into"),
("lin_returned","Devolvió su resultado","Returned its result"),
("lin_return","↩ Devolver el resultado","↩ Return the result"),
("lin_trazo","Ver el trazo","See the trace"),
("lin_return_title","Devolver el resultado","Return the result"),
("lin_return_body","Se publica en «%1$s» como cierre de esta derivada. Quienes están allí lo verán aunque no participen aquí.","It is posted in “%1$s” as the close of this branch. People there will see it even if they are not part of this one."),
("lin_return_send","Devolver","Return"),
("lin_result_of","Resultado de «%1$s»","Result of “%1$s”"),
("lin_result_hidden","Resultado de una conversación derivada","Result of a branched conversation"),
("lin_open","Abrir","Open"),
("lin_kind_same","Misma audiencia","Same audience"),
("lin_kind_internal","Interno","Internal"),
("lin_kind_directive","Directivo","Leadership"),
("trazo_sub","Una conversación se deriva en otra cuando hay que resolver algo aparte —con el equipo, con otra empresa, con dirección— y se vuelve a conectar cuando devuelve su resultado. Aquí ves cada recorrido completo.","A conversation branches into another when something has to be solved separately —with the team, with another company, with leadership— and reconnects when it returns its result. Here you see each full journey."),
("trazo_empty","Aún no hay conversaciones derivadas en tu alcance. Deriva una desde cualquier mensaje con «⑂ Derivar».","There are no branched conversations in your scope yet. Branch one from any message with “⑂ Branch”."),
("trazo_open","Abierta","Open"),
("trazo_returned_on","Devuelta %1$s","Returned %1$s"),
("trazo_tramos","%1$d tramos","%1$d legs"),
# Sistema
("sys_issue_created","Abrió el asunto «%1$s».","Opened the issue “%1$s”."),
("sys_issue_closed","Cerró el asunto «%1$s».","Closed the issue “%1$s”."),
("sys_issue_reopened","Reabrió el asunto «%1$s».","Reopened the issue “%1$s”."),
("sys_derived_here","Conversación derivada de «%1$s»: «%2$s»","Branched from “%1$s”: “%2$s”"),
("sys_derived_from","Se derivó una conversación desde aquí.","A conversation was branched from here."),
("sys_returned","Esta conversación devolvió su resultado al origen.","This conversation returned its result to its origin."),
("sys_event_created","Agendó «%1$s» para el %2$s.","Scheduled “%1$s” for %2$s."),
("sys_event_moved","Movió «%1$s» al %2$s.","Moved “%1$s” to %2$s."),
("sys_event_cancelled","Canceló la reunión «%1$s».","Cancelled the meeting “%1$s”."),
# Agenda
("cal_today","Hoy","Today"),
("cal_prev","Semana anterior","Previous week"),
("cal_next","Semana siguiente","Next week"),
("cal_new","＋ Reunión","＋ Meeting"),
("cal_new_title","Nueva reunión","New meeting"),
("cal_edit_title","Editar reunión","Edit meeting"),
("cal_title","Título","Title"),
("cal_conversation","Grupo","Group"),
("cal_date","Fecha","Date"),
("cal_start","Inicio","Start"),
("cal_end","Fin","End"),
("cal_tz","Zona horaria","Time zone"),
("cal_location","Lugar o enlace de la reunión","Place or meeting link"),
("cal_location_ph","Sala, dirección o enlace de Meet, Teams o Zoom","Room, address or a Meet, Teams or Zoom link"),
("cal_invitees","Invitados","Invitees"),
("cal_description","Notas (opcional)","Notes (optional)"),
("cal_save","Guardar","Save"),
("cal_create","Agendar","Schedule"),
("cal_organizer","Organiza %1$s","Organised by %1$s"),
("cal_rsvp_yes","Asistiré","Going"),
("cal_rsvp_no","No asistiré","Not going"),
("cal_rsvp_maybe","Tal vez","Maybe"),
("cal_rsvp_pending","Sin responder","No reply"),
("cal_add_google","Google Calendar","Google Calendar"),
("cal_add_outlook","Outlook","Outlook"),
("cal_add_to","Agregar a tu calendario","Add to your calendar"),
("cal_add_device","Calendario del teléfono","Phone calendar"),
("cal_join","Unirse","Join"),
("cal_open_chat","Abrir conversación","Open conversation"),
("cal_cancel","Cancelar reunión","Cancel meeting"),
("cal_cancel_confirm","¿Cancelar esta reunión? Se avisará en el grupo.","Cancel this meeting? The group will be notified."),
("cal_cancelled","Cancelada","Cancelled"),
("cal_empty","No hay reuniones esta semana.","No meetings this week."),
("cal_upcoming","Próximas reuniones","Upcoming meetings"),
("cal_no_upcoming","Sin reuniones próximas en este grupo.","No upcoming meetings in this group."),
("cal_event_tz","Hora del evento","Event time"),
("cal_edit","Editar","Edit"),
("cal_week","Semana del %1$s","Week of %1$s"),
("cal_notif_created","Nueva reunión: %1$s","New meeting: %1$s"),
("cal_notif_moved","Reunión movida: %1$s","Meeting moved: %1$s"),
("cal_notif_cancelled","Reunión cancelada: %1$s","Meeting cancelled: %1$s"),
# WhatsApp
("wa_title","WhatsApp","WhatsApp"),
("wa_connect","＋ Conectar WhatsApp","＋ Connect WhatsApp"),
("wa_intro","Conecta tu WhatsApp personal y tu WhatsApp Business. TieComs lee tus grupos y chats como un dispositivo vinculado y los organiza por tema; nada cambia en tu teléfono.","Connect your personal WhatsApp and your WhatsApp Business. TieComs reads your groups and chats as a linked device and organises them by topic; nothing changes on your phone."),
("wa_empty_title","Conecta tus WhatsApp","Connect your WhatsApps"),
("wa_empty_body","Hoy casi todos tenemos dos: el personal y el Business. Conéctalos los dos y mira todos tus grupos ordenados en un solo lugar.","Most of us have two these days: personal and Business. Connect both and see all your groups organised in one place."),
("wa_connect_title","Conectar WhatsApp","Connect WhatsApp"),
("wa_connect_body","¿Cuál vas a conectar? Luego puedes agregar el otro.","Which one are you connecting? You can add the other one later."),
("wa_kind_personal","Tu número personal: familia, amigos, grupos del trabajo.","Your personal number: family, friends, work groups."),
("wa_kind_business","El número de tu negocio: clientes, pedidos, soporte.","Your business number: customers, orders, support."),
("wa_personal","Personal","Personal"),
("wa_label","Nombre para reconocerla","A name to recognise it"),
("wa_with_qr","Escanear QR","Scan QR"),
("wa_with_phone","Código con mi número","Code with my number"),
("wa_phone","Número de esa cuenta, con indicativo","That account's number, with country code"),
("wa_phone_ph","+57 300 123 4567","+57 300 123 4567"),
("wa_phone_hint","Útil si estás en el mismo teléfono y no puedes escanear. WhatsApp te pedirá un código de 8 letras.","Useful if you are on the same phone and cannot scan. WhatsApp will ask you for an 8-letter code."),
("wa_privacy","Solo tú ves estos chats. TieComs no envía mensajes ni marca nada como leído. Puedes desconectar cuando quieras y se borra todo.","Only you see these chats. TieComs does not send messages or mark anything as read. You can disconnect at any time and everything is deleted."),
("wa_start","Generar código","Generate code"),
("wa_linking","Preparando el código…","Preparing the code…"),
("wa_preparing","Pidiendo el código a WhatsApp…","Asking WhatsApp for the code…"),
("wa_pairing_code","Código de vinculación","Pairing code"),
("wa_qr_alt","Código QR para vincular WhatsApp","QR code to link WhatsApp"),
("wa_step1","Abre WhatsApp en tu teléfono.","Open WhatsApp on your phone."),
("wa_step1b","Abre WhatsApp Business en tu teléfono.","Open WhatsApp Business on your phone."),
("wa_step2","Ve a Ajustes › Dispositivos vinculados › Vincular un dispositivo.","Go to Settings › Linked devices › Link a device."),
("wa_step3","Escanea este código. Cambia cada ~20 segundos.","Scan this code. It changes every ~20 seconds."),
("wa_step3code","Toca «Vincular con el número de teléfono» y escribe este código.","Tap “Link with phone number” and type this code."),
("wa_status_pending","Preparando","Preparing"),
("wa_status_qr","Esperando que escanees","Waiting for you to scan"),
("wa_status_connected","Conectada","Connected"),
("wa_status_reconnecting","Reconectando…","Reconnecting…"),
("wa_status_expired","El código venció","The code expired"),
("wa_status_logged_out","Se cerró desde el teléfono","Signed out from the phone"),
("wa_status_error","No se pudo conectar","Could not connect"),
("wa_counts","%1$d chats · %2$d grupos","%1$d chats · %2$d groups"),
("wa_new_code","Generar otro código","Generate another code"),
("wa_use_phone","Mejor con mi número","Use my number instead"),
("wa_use_qr","Mejor con QR","Use QR instead"),
("wa_disconnect","Desconectar","Disconnect"),
("wa_disconnect_confirm","¿Desconectar «%1$s»? Se cierra la sesión en WhatsApp y se borran de TieComs sus chats.","Disconnect “%1$s”? The WhatsApp session is closed and its chats are deleted from TieComs."),
("wa_organizer","Tus chats, organizados","Your chats, organised"),
("wa_reorganize","Organizar de nuevo","Organise again"),
("wa_organized","Listo: %1$d chats cambiaron de categoría","Done: %1$d chats changed category"),
("wa_cat_all","Todos","All"),
("wa_cat_trabajo","Trabajo","Work"),
("wa_cat_clientes","Clientes","Customers"),
("wa_cat_familia","Familia","Family"),
("wa_cat_amigos","Amigos","Friends"),
("wa_cat_comunidad","Comunidad","Community"),
("wa_cat_otros","Otros","Other"),
("wa_search","Buscar grupo o chat","Search group or chat"),
("wa_all_accounts","Todas las cuentas","All accounts"),
("wa_groups","Grupos","Groups"),
("wa_all_chats","Todos los chats","All chats"),
("wa_show_hidden","Ver ocultos","Show hidden"),
("wa_no_chats","Nada en esta categoría.","Nothing in this category."),
("wa_syncing","Cuando conectes una cuenta, tus grupos aparecen aquí en unos segundos.","When you connect an account, your groups show up here within seconds."),
("wa_members","%1$d miembros","%1$d members"),
("wa_category","Categoría","Category"),
("wa_manual","La elegiste tú","You chose it"),
("wa_suggested","Sugerida por TieComs","Suggested by TieComs"),
("wa_no_messages","Aún no hay mensajes guardados de este chat. Llegan los nuevos y parte del historial.","No saved messages from this chat yet. New ones and part of the history arrive."),
("wa_pin","📌 Fijar","📌 Pin"),
("wa_unpin","Quitar fijado","Unpin"),
("wa_hide","Ocultar","Hide"),
("wa_unhide","Mostrar","Show"),
("wa_reset_category","Volver a la sugerida","Back to suggested"),
("wa_link_to","Traer los mensajes nuevos a una conversación de TieComs","Bring new messages into a TieComs conversation"),
("wa_not_linked","No vincular","Do not link"),
("wa_link_hint","Los mensajes nuevos de este chat llegarán allí como «reenviado de WhatsApp», a tu nombre.","New messages from this chat will arrive there as “forwarded from WhatsApp”, under your name."),
("wa_linked_hint","Los mensajes nuevos llegan a %1$s","New messages arrive in %1$s"),
("settings_whatsapp_hint","Conecta tu WhatsApp personal y el Business para ver tus grupos organizados.","Connect your personal WhatsApp and Business to see your groups organised."),
("settings_team","Tu empresa","Your company"),
# Dominios (nativo: la web aún no tiene esta pantalla)
("dom_title","Dominios verificados","Verified domains"),
("dom_hint","Quien entre con un correo de estos dominios queda asociado a tu empresa. Verifica con un registro TXT en tu DNS o entrando con Google Workspace / Microsoft Entra.","People who sign in with an email on these domains are linked to your company. Verify with a TXT record in your DNS or by signing in with Google Workspace / Microsoft Entra."),
("dom_add","Agregar dominio","Add domain"),
("dom_add_ph","tuempresa.com","yourcompany.com"),
("dom_verify","Verificar","Verify"),
("dom_pending","Pendiente de verificar","Pending verification"),
("dom_idp","Verificado por Google o Microsoft","Verified by Google or Microsoft"),
("dom_dns","Verificado por DNS","Verified by DNS"),
("dom_txt","Crea este registro TXT: %1$s → %2$s","Create this TXT record: %1$s → %2$s"),
("dom_empty","Aún no hay dominios.","No domains yet."),
("dom_only_admins","Solo quien administra la empresa puede gestionar sus dominios.","Only company admins can manage its domains."),
("org_verified","Empresa verificada · %1$s","Verified company · %1$s"),
# Eliminar cuenta (nativo, contrato DELETE /api/v1/account)
("del_title","Eliminar cuenta","Delete account"),
("del_row_hint","Borra tu cuenta de TieComs de forma permanente.","Permanently delete your TieComs account."),
("del_intro","Esta acción no se puede deshacer.","This cannot be undone."),
("del_what_goes","Se borra: tu nombre, correo y contraseña, los accesos con Google o Microsoft, tus recordatorios y preferencias, los WhatsApp que conectaste y tu participación en empresas, espacios y conversaciones. Se cierran todas tus sesiones.","Deleted: your name, email and password, Google or Microsoft sign-ins, your reminders and preferences, the WhatsApp accounts you connected and your membership in companies, spaces and conversations. All your sessions are closed."),
("del_what_stays","Se conserva: los mensajes que escribiste en espacios compartidos, como registro de las empresas, pero ya sin tu nombre. Si eras la única persona dueña de tu empresa, la administración pasa a quien lleve más tiempo.","Kept: the messages you wrote in shared spaces, as the companies' record, but no longer with your name. If you were the only owner of your company, admin rights go to the longest-standing member."),
("del_email","Escribe tu correo para confirmar","Type your email to confirm"),
("del_password","Tu contraseña","Your password"),
("del_password_hint","Si entras solo con Google o Microsoft, déjala vacía.","If you only sign in with Google or Microsoft, leave it empty."),
("del_button","Eliminar mi cuenta","Delete my account"),
("del_email_mismatch","El correo no coincide con el de tu cuenta.","The email does not match your account."),
("del_wrong_password","Contraseña incorrecta.","Wrong password."),
("del_password_needed","Esta cuenta tiene contraseña: escríbela para confirmar.","This account has a password: type it to confirm."),
("del_done","Tu cuenta se eliminó.","Your account was deleted."),
# Varios (nativo)
("home_shortcuts","Accesos","Shortcuts"),
("today_list","Hoy en tu agenda","Today in your agenda"),
("participants_n","%1$d participantes","%1$d participants"),
("loading_generic","Cargando…","Loading…"),
("close","Cerrar","Close"),
("undo","Deshacer","Undo"),
("select_conversation","Elige la conversación","Choose the conversation"),
]


if __name__ == "__main__":
    # Regenera app/src/main/res/values{,-es}/strings_v2.xml (inglés por defecto, español en values-es).
    import os, re
    R = os.path.join(os.path.dirname(__file__), "..", "app", "src", "main", "res")
    existing = set(re.findall(r'name="([^"]+)"', open(os.path.join(R, "values", "strings.xml")).read()))
    def esc(v): return v.replace("&", "&amp;").replace("<", "&lt;").replace("'", "\\'").replace('"', '\\"')
    for d, idx in (("values", 2), ("values-es", 1)):
        out = ['<?xml version="1.0" encoding="utf-8"?>', '<!-- Generado con tools/strings_v2.py: textos de la web (apps/web/src/i18n.ts). -->', '<resources>']
        out += [f'    <string name="{r[0]}">{esc(r[idx])}</string>' for r in S if r[0] not in existing]
        out.append('</resources>')
        open(os.path.join(R, d, "strings_v2.xml"), "w").write("\n".join(out) + "\n")
